//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更此檔案可能會導致不正確的行為，而且若已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsSSOReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginDetail", Namespace="http://tempuri.org/")]
    public partial class LoginDetail : object
    {
        
        private string strSystemField;
        
        private string strUserIDField;
        
        private string strUserPWDField;
        
        private System.DateTime dtmLoginField;
        
        private string strCodeStringField;
        
        private bool isSuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string strSystem
        {
            get
            {
                return this.strSystemField;
            }
            set
            {
                this.strSystemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string strUserID
        {
            get
            {
                return this.strUserIDField;
            }
            set
            {
                this.strUserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string strUserPWD
        {
            get
            {
                return this.strUserPWDField;
            }
            set
            {
                this.strUserPWDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime dtmLogin
        {
            get
            {
                return this.dtmLoginField;
            }
            set
            {
                this.dtmLoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strCodeString
        {
            get
            {
                return this.strCodeStringField;
            }
            set
            {
                this.strCodeStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool isSuccess
        {
            get
            {
                return this.isSuccessField;
            }
            set
            {
                this.isSuccessField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsSSOReference.wsSSOSoap")]
    public interface wsSSOSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginByCodeString", ReplyAction="*")]
        System.Threading.Tasks.Task<wsSSOReference.LoginByCodeStringResponse> LoginByCodeStringAsync(wsSSOReference.LoginByCodeStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginByUser", ReplyAction="*")]
        System.Threading.Tasks.Task<wsSSOReference.LoginByUserResponse> LoginByUserAsync(wsSSOReference.LoginByUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginByCodeStringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginByCodeString", Namespace="http://tempuri.org/", Order=0)]
        public wsSSOReference.LoginByCodeStringRequestBody Body;
        
        public LoginByCodeStringRequest()
        {
        }
        
        public LoginByCodeStringRequest(wsSSOReference.LoginByCodeStringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginByCodeStringRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wsSSOReference.LoginDetail Detail;
        
        public LoginByCodeStringRequestBody()
        {
        }
        
        public LoginByCodeStringRequestBody(wsSSOReference.LoginDetail Detail)
        {
            this.Detail = Detail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginByCodeStringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginByCodeStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsSSOReference.LoginByCodeStringResponseBody Body;
        
        public LoginByCodeStringResponse()
        {
        }
        
        public LoginByCodeStringResponse(wsSSOReference.LoginByCodeStringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginByCodeStringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginByCodeStringResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public wsSSOReference.LoginDetail Detail;
        
        public LoginByCodeStringResponseBody()
        {
        }
        
        public LoginByCodeStringResponseBody(string LoginByCodeStringResult, wsSSOReference.LoginDetail Detail)
        {
            this.LoginByCodeStringResult = LoginByCodeStringResult;
            this.Detail = Detail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginByUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginByUser", Namespace="http://tempuri.org/", Order=0)]
        public wsSSOReference.LoginByUserRequestBody Body;
        
        public LoginByUserRequest()
        {
        }
        
        public LoginByUserRequest(wsSSOReference.LoginByUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginByUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wsSSOReference.LoginDetail Detail;
        
        public LoginByUserRequestBody()
        {
        }
        
        public LoginByUserRequestBody(wsSSOReference.LoginDetail Detail)
        {
            this.Detail = Detail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginByUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginByUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsSSOReference.LoginByUserResponseBody Body;
        
        public LoginByUserResponse()
        {
        }
        
        public LoginByUserResponse(wsSSOReference.LoginByUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginByUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginByUserResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public wsSSOReference.LoginDetail Detail;
        
        public LoginByUserResponseBody()
        {
        }
        
        public LoginByUserResponseBody(string LoginByUserResult, wsSSOReference.LoginDetail Detail)
        {
            this.LoginByUserResult = LoginByUserResult;
            this.Detail = Detail;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface wsSSOSoapChannel : wsSSOReference.wsSSOSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class wsSSOSoapClient : System.ServiceModel.ClientBase<wsSSOReference.wsSSOSoap>, wsSSOReference.wsSSOSoap
    {
        
        /// <summary>
        /// 實作此部分方法來設定服務端點。
        /// </summary>
        /// <param name="serviceEndpoint">要設定的端點</param>
        /// <param name="clientCredentials">用戶端認證</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsSSOSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsSSOSoapClient.GetBindingForEndpoint(endpointConfiguration), wsSSOSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsSSOSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsSSOSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsSSOSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsSSOSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsSSOSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSSOReference.LoginByCodeStringResponse> wsSSOReference.wsSSOSoap.LoginByCodeStringAsync(wsSSOReference.LoginByCodeStringRequest request)
        {
            return base.Channel.LoginByCodeStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsSSOReference.LoginByCodeStringResponse> LoginByCodeStringAsync(wsSSOReference.LoginDetail Detail)
        {
            wsSSOReference.LoginByCodeStringRequest inValue = new wsSSOReference.LoginByCodeStringRequest();
            inValue.Body = new wsSSOReference.LoginByCodeStringRequestBody();
            inValue.Body.Detail = Detail;
            return ((wsSSOReference.wsSSOSoap)(this)).LoginByCodeStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSSOReference.LoginByUserResponse> wsSSOReference.wsSSOSoap.LoginByUserAsync(wsSSOReference.LoginByUserRequest request)
        {
            return base.Channel.LoginByUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsSSOReference.LoginByUserResponse> LoginByUserAsync(wsSSOReference.LoginDetail Detail)
        {
            wsSSOReference.LoginByUserRequest inValue = new wsSSOReference.LoginByUserRequest();
            inValue.Body = new wsSSOReference.LoginByUserRequestBody();
            inValue.Body.Detail = Detail;
            return ((wsSSOReference.wsSSOSoap)(this)).LoginByUserAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsSSOSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsSSOSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsSSOSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.10.34/eip/wsSSO.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsSSOSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.10.34/eip/wsSSO.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsSSOSoap,
            
            wsSSOSoap12,
        }
    }
}
